# Generated by Django 5.2 on 2025-04-18 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(default='P0000', max_length=100)),
                ('product_name', models.CharField(default='Unnamed Product', max_length=255)),
                ('product_type', models.CharField(default='GenericType', max_length=100)),
                ('unit_size', models.CharField(default='N/A', max_length=100)),
                ('brand', models.CharField(default='GenericBrand', max_length=100)),
                ('date_received', models.CharField(default='2020-01-01', max_length=50)),
                ('supplier', models.CharField(default='Unknown Supplier', max_length=255)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('batch_number', models.CharField(default='N/A', max_length=100)),
                ('expiration_date', models.CharField(default='2021-01-01', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.CharField(default='2020-01-01', max_length=50)),
                ('expected_delivery', models.CharField(default='2021-01-01', max_length=50)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Canceled', 'Canceled')], default='Pending', max_length=20)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suppliers.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('movement_type', models.CharField(choices=[('IN', 'In'), ('OUT', 'Out')], default='IN', max_length=50)),
                ('date_moved', models.CharField(default='2020-01-01', max_length=50)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='inventory.product')),
            ],
            options={
                'ordering': ['date_moved'],
            },
        ),
    ]
