# Generated by Django 5.2 on 2025-04-18 13:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_product_date_received_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date_received',
            field=models.DateField(default=datetime.date(2017, 1, 1)),
        ),
        migrations.AlterField(
            model_name='product',
            name='expiration_date',
            field=models.DateField(default=datetime.date(2017, 1, 1)),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='expected_delivery',
            field=models.DateField(default=datetime.date(2021, 1, 1)),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='order_date',
            field=models.DateField(default=datetime.date(2020, 1, 1)),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='date_moved',
            field=models.DateField(default=datetime.date(2020, 1, 1)),
        ),
    ]
